FROM python:3.12-slim AS base

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

FROM base AS base_extended

RUN apt-get update && apt-get install -y --no-install-recommends \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
    libpq-dev \
    gettext \
    && rm -rf /var/lib/apt/lists/*

FROM base_extended AS dependencies

WORKDIR /app
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM dependencies AS application

ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY ./items ./items
CMD ["python", "items/manage.py", "runserver", "0.0.0.0:8000"]