# Generated by Django 5.0.1 on 2024-01-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ean13', models.CharField(max_length=13, verbose_name='Code EAN13')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'item scan',
                'verbose_name_plural': 'item scans',
                'ordering': ['-timestamp'],
            },
        ),
    ]
