# Generated by Django 5.0.1 on 2024-01-18 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscan',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
