# Generated by Django 5.0.1 on 2024-01-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0002_alter_itemscan_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('token', models.CharField(max_length=50, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.AddField(
            model_name='itemscan',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='itemscan.device', verbose_name='Device'),
            preserve_default=False,
        ),
    ]
