# Generated by Django 5.0.1 on 2024-01-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0003_device_itemscan_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Token'),
        ),
    ]
