# Generated by Django 5.0.1 on 2024-01-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0004_alter_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
