# Generated by Django 5.0.1 on 2024-01-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0005_device_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(max_length=100, unique=True, verbose_name='Location'),
        ),
    ]
