# Generated by Django 5.0.1 on 2024-01-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0006_alter_device_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, unique=True, verbose_name='Action')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'scan action',
                'verbose_name_plural': 'scan actions',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AddField(
            model_name='itemscan',
            name='action',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='itemscan.scanaction', verbose_name='Action'),
            preserve_default=False,
        ),
    ]
