# Generated by Django 5.0.1 on 2024-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0007_scanaction_alter_device_options_itemscan_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Token'),
        ),
    ]
