# Generated by Django 5.0.1 on 2024-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0009_alter_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='Token'),
        ),
    ]
