# Generated by Django 5.0.2 on 2024-02-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0010_alter_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanaction',
            name='action',
        ),
    ]
