# Generated by Django 5.0.2 on 2024-02-29 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0011_remove_scanaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanaction',
            name='name',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
