# Generated by Django 5.0.2 on 2024-02-29 09:52

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    ScanAction = apps.get_model("itemscan", "scanaction")
    for row in ScanAction.objects.all():
        row.name = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0012_scanaction_name'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
