# Generated by Django 5.0.2 on 2024-02-29 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0013_auto_20240229_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanaction',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
