# Generated by Django 5.0.2 on 2024-02-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemscan', '0014_auto_20240229_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemscan',
            name='code_ean13',
        ),
        migrations.AddField(
            model_name='itemscan',
            name='code',
            field=models.CharField(default='0', max_length=20, verbose_name='Code'),
        ),
    ]
